### ISSUE TITLE
Exception encountered due to missing X11 DISPLAY variable or lack of headful library support

### ISSUE THREAD

**Issue by IncasedDevelopment** [NullPounce/pounce-keys#10]
When running the command java -jar MessageListener.jar, an exception occurs indicating a java.awt.HeadlessException with the following message:
```
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/java.awt.Frame.<init>(Frame.java:393)
        at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
        at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
        at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
        at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:875)
        at java.desktop/javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:806)
        at java.desktop/javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:768)
        at java.desktop/javax.swing.JOptionPane.showConfirmDialog(JOptionPane.java:729)
        at MessageListener.main(MessageListener.java:65)
```
## Steps to Reproduce:

- Execute the command java -jar MessageListener.jar.

**Comment by NullPounce** [comment]
see new updates
